version: '3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ~/.dvmn/redis/d–∞ta:/root/redis
      - ~/.dvmn/redis/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env
